AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Name:
    Type: String
    Default: "offcourse"
  Stage:
    Type: String

    Default: "dev"
esources:
  # AssetsBucket:
  #   Type: "AWS::S3::Bucket"
  #   Properties: 
  #     WebsiteConfiguration:
  #       ErrorDocument: "index.html"
  #       IndexDocument: "index.html"
  # AssetsPolicy: 
  #   Type: "AWS::S3::BucketPolicy"
  #   Properties: 
  #     Bucket:
  #       Ref: "AssetsBucket"
  #     PolicyDocument: 
  #       Statement: 
  #         - Action: 
  #             - "s3:GetObject"
  #           Effect: "Allow"
  #           Resource:
  #             Fn::Join: ["", ["arn:aws:s3:::", { "Ref" : "AssetsBucket" }, "/*" ]]
  #           Principal: "*"


  RawDataBucket:
    Type: "AWS::S3::Bucket"
  RawDataPolicy: 
    Type: "AWS::S3::BucketPolicy"
    Properties: 
      Bucket:
        Ref: RawDataBucket
      PolicyDocument: 
        Statement: 
          - Action: 
              - "s3:PutObject"
            Effect: "Allow"
            Resource:
              Fn::Join: ["", ["arn:aws:s3:::", { "Ref" : "RawDataBucket" }, "/*" ]]
            Principal: "*"

Outputs:
  RawDataBucketName:
    Description: Name of the RawData Bucket
    Value: !Ref RawDataBucket
    Export:
      Name: "${Name}-RawDataBucket-${Stage}"

