AWSTemplateFormatVersion: "2010-09-09"

Resources:
  IdentitiesStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1

  CoursesStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1

  ProfilesStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1

  PortraitsStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1

  BookmarksStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1

  ResourcesStream:
    Type: AWS::Kinesis::Stream
    DependsOn: IdentitiesStream
    Properties:
      ShardCount: 1

  RawUsersStream:
    Type: AWS::Kinesis::Stream
    DependsOn: CoursesStream
    Properties:
      ShardCount: 1

  RawPortraitsStream:
    Type: AWS::Kinesis::Stream
    DependsOn: ProfilesStream
    Properties:
      ShardCount: 1

  RawResourcesStream:
    Type: AWS::Kinesis::Stream
    DependsOn: PortraitsStream
    Properties:
      ShardCount: 1

  RawCoursesStream:
    Type: AWS::Kinesis::Stream
    DependsOn: BookmarksStream
    Properties:
      ShardCount: 1

  RawGithubReposStream:
    Type: AWS::Kinesis::Stream
    DependsOn: ResourcesStream
    Properties:
      ShardCount: 1

  GithubCoursesStream:
    Type: AWS::Kinesis::Stream
    DependsOn: RawUsersStream
    Properties:
      ShardCount: 1

  RawGithubCoursesStream:
    Type: AWS::Kinesis::Stream
    DependsOn: RawPortraitsStream
    Properties:
      ShardCount: 1

  GithubReposStream:
    Type: AWS::Kinesis::Stream
    DependsOn: RawResourcesStream
    Properties:
      ShardCount: 1

  ErrorsStream:
    Type: AWS::Kinesis::Stream
    DependsOn: RawCoursesStream
    Properties:
      ShardCount: 1
